### ISSUE TITLE
Server stats have no data

### ISSUE THREAD

**Issue by SKFrozenCloud** [dappnode/DAppNodePackage-DMS#21]
**Describe the bug**

When I go to the grafana dashboard all the data is there except for all the server related data.
But the memory usage of the beacon and validator nodes are present.
See picture: https://imgur.com/a/S4t3q4I

**To Reproduce**

1. Install the package
2. Go to the dashboard
3. See error

**Expected behavior**

I expected to see server stats.

**Screenshots**

https://imgur.com/a/S4t3q4I

**DAppNode version:**

- Package version: 1.0.2
- OS: Dappnode (custom computer)
- Browser: Firefox

**Additional context**

When I tried to edit the cpu and checked the query I noticed that `node_cpu_seconds_total` does not autocomplete when I wrote it on a new query.

**Comment by pablomendezroyo** [comment]
which is your dappnode setup?
- is it a dappnode that you bought?
- Is it a dappnode that you install by yourself? if so please give details about the host machine

**Comment by SKFrozenCloud** [comment]
I installed DappNode on a custom build computer. I then installed Geth and Prysm and then lastly the DMS

i3 10100F
GTX 1050 TI (is only used for display)
