### ISSUE TITLE
Grafana Docker Dash Doesn't show Prysm Prater Metrics

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-DMS#26]
**Describe the bug**
The grafana docker dashboard doesn't appear to show Prysm Prater Beacon-chain and Validator.  when running a mainnet prysm package at the same time.  they appear to be combined into one service for each sub-service, both mainnet and prater beaconchain, and then both mainnet and prater validators.

**To Reproduce**
Install DMS, DAppNodeExporter, Prysm Prater, GoerliEth, geth light, and prysm.
let everything sync and go to the dms dashboard for docker and you will see what seems to be an outsize amount of resources dedicated to beacon-chain, and validator.  shut off the prysm and youll se a huge drop in resource usage but not entirely. it continues to run at prater speed.

**Expected behavior**
I would expect to see a beacon chain metric, a prater beacon chain metric, a prysm validator metric, and a prysm prater validator metric

**Screenshots**
*with both prater and mainnet running*
<img width="1440" alt="Screen Shot 2021-12-05 at 4 53 07 AM" src="https://user-images.githubusercontent.com/4649787/144743784-0d6275eb-5c72-4100-85ae-a91e56b50b30.png">
*shut off mainnet prysm*
<img width="1440" alt="Screen Shot 2021-12-05 at 4 57 17 AM" src="https://user-images.githubusercontent.com/4649787/144743812-11c3d6b7-d26d-4aa6-9f89-ab7cd4e45100.png">
*dashboard after shutting off prysm mainnet*
<img width="1440" alt="Screen Shot 2021-12-05 at 4 56 47 AM" src="https://user-images.githubusercontent.com/4649787/144743830-d4792832-d7ff-46bc-9221-ac8f44b82e6a.png">

**DAppNode version:**
@mgarciate sees the same, and i see it on all 5 of my dappnodes

**Comment by alexpeterson91** [comment]
to be fixed by [Fix #28 Prysm Prater does not designate its activities BeaconChain and Validator, Grafana fix](https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/29)

**Comment by alexpeterson91** [comment]
Grafana still shows only 1 beacon-chain application, and 1 validator application, for every instance of Prysm, combining them all, so if you have Prysm, Prysm Prater, and Gnosis Beacon Chain Prysm, they are all combined into one service for each sub service so on grafana you see just beacon chain, but its actually a combo of all prysm applications you have installed, testnets, gnosis, mainnet etc, need to make it show them as different its making troubleshooting impossible.  Screenshot clearly showing how at least prater and mainnet are combined was in the first post of this issue.  @mgarciate @eduadiez @tropicar https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/29 did not fix this or https://github.com/dappnode/DAppNodePackage-prysm-prater/issue/28

**Comment by mgarciate** [comment]
> Grafana still shows only 1 beacon-chain application, and 1 validator application, for every instance of Prysm, combining them all, so if you have Prysm, Prysm Prater, and Gnosis Beacon Chain Prysm, they are all combined into one service for each sub service so on grafana you see just beacon chain, but its actually a combo of all prysm applications you have installed, testnets, gnosis, mainnet etc, need to make it show them as different its making troubleshooting impossible. Screenshot clearly showing how at least prater and mainnet are combined was in the first post of this issue. @mgarciate @eduadiez @tropicar [dappnode/DAppNodePackage-prysm-prater#29](https://github.com/dappnode/DAppNodePackage-prysm-prater/pull/29) did not fix this or https://github.com/dappnode/DAppNodePackage-prysm-prater/issue/28 as it was supposed to.
> The situation is now worse with the GBC prysm being a package on DAppNode, since it also combines

@alexpeterson91 @eduadiez @tropicar @dapplion I'm working on it. I'll create a PR today.

**Comment by mgarciate** [comment]
@eduadiez @tropicar @alexpeterson91 Created PR https://github.com/dappnode/DAppNodePackage-exporter/pull/8
Check new dashboard at https://github.com/mgarciate/DAppNodePackage-exporter/blob/fix/7_ungroup_usage_same_name_services/docker-grafana-dashboard.json

**Comment by alexpeterson91** [comment]
> @eduadiez @tropicar @alexpeterson91 Created PR https://github.com/dappnode/DAppNodePackage-exporter/pull/8
> 
> Check new dashboard at https://github.com/mgarciate/DAppNodePackage-exporter/blob/fix/7_ungroup_usage_same_name_services/docker-grafana-dashboard.json

Works great for me this linked PR does fix this issue fully for me. On all machines.
