### ISSUE TITLE
Cannot Star Dashboards

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DAppNodePackage-DMS#30]
**Describe the bug**

A User was recently looking for more control over grafana, and specifically wanted to be able to star dashboards to set a default, but couldn't.

**To Reproduce**

open DMS on a DAppNode with dappnode exporter installed or other packages including dashboards.
navigate to the grafana home page where you can see a list of installed/imported dashboards.  There is a star at the end of each, clicking it should favorite(?) it so that it can be selected as the default.  
It will fail and show an `Unauthorized` Error

**Expected behavior**
should properly mark the selected dashboard as starred

**Screenshots**
<img width="1440" alt="Screen Shot 2022-02-09 at 5 17 39 PM" src="https://user-images.githubusercontent.com/4649787/153307164-6e814ad2-dfe7-49c6-9c58-ec46150c0af1.png">

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

appears issue is due to credentials but i am not sure how grafana credentials work, the dockerfile runs it in root so that could be why a normal user cannot but i really don't know grafana well enough.  @tropicar please assist when available

**Comment by dapplion** [comment]
Grafana has some initial configuration on who is the default user and what persmisions does it has. @tropicar dig the grafana docs for the config .ini file

**Comment by alexpeterson91** [comment]
@tropicar can you check on this?

**Comment by dapplion** [comment]
> @tropicar can you check on this?

In one month maybe? hahaha

**Comment by tropicar** [comment]
In the configuration file of grafana, we use 2 configurations that can affect to this I think:
- enable anonymous access -> this one let the users access the grafana dashboards with no login
- org_role = admin -> It will give the admin-level permissions to the anonymous users
I think the feature of having favourites is only for users(non anonymous users), I am checking out and asking on grafana support if there is some easy solution
Sorry for the delayed answer

**Comment by tropicar** [comment]
One possible solution would be:
- Go to http://dms.dappnode/org/users configurations > users - > create an invitation for users (yourself for example)
- Copy the link you obtain, paste into the browser while you are connected to the VPN,  and define the user, password and email, so, now on the grafana server you will have a user, so you can mark your favourite dashboards.
All this configurations are happening locally in the grafana server that is allocated in the dappnode

**Comment by tropicar** [comment]
I think this "problem" was clarified although the error was not caused by dappnode or DMS package, I think would be interesting to add some basic configuration, stuff of the dms package in the documentation.
