### ISSUE TITLE
Update grafana / prometheus to the latest version.

### ISSUE THREAD

**Issue by mfw78** [dappnode/DAppNodePackage-DMS#37]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated that when I want to import a dashboard from another project, it is incompatible and requires manual manipulation to get it to work with dappnode's Grafana.

**Describe the solution you'd like**

Update, current versions of Grafana and Prometheus.

**Describe alternatives you've considered**

Lots of manual work.

**Comment by Marketen** [comment]
we need to carefully test grafana here since its a major version change, from 9 to 10. Here are all the breaking changes:
https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v10-0/

**Comment by Marketen** [comment]
in dms 2.0.0, we updated both grafana & prometheus to latest versions
